---
- name: Determine public ip address
  uri:
    url: http://ipv4bot.whatismyipaddress.com/
    return_content: true
  register: get_whatismyipaddress

- name: Set management_source_ip
  set_fact:
    management_source_ip: "{{ get_whatismyipaddress.content }}"
