---
openshift_disable_check: memory_availability,disk_availability

openshift_provision_node_groups:
  master:
    instance_count: 1
    labels:
      logging-infra-fluentd: "true"
      node-role.kubernetes.io/master: "true"
  infra-app:
    instance_count: 1
    labels:
      logging-infra-fluentd: "true"
      node-role.kubernetes.io/infra: "true"
      node-role.kubernetes.io/infra-app: "true"
  router:
    instance_count: 1
    labels:
      logging-infra-fluentd: "true"
      node-role.kubernetes.io/infra: "true"
      node-role.kubernetes.io/router: "true"
  compute:
    instance_count: 1
    labels:
      logging-infra-fluentd: "true"
      node-role.kubernetes.io/compute: "true"
