---
- name: Run terrafom configure
  hosts: localhost
  connection: local
  tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role for bootstrap
    include_role:
      name: "{{ openshift_provision_cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: apply
      terraform_components:
      - network
      - service-accounts
      - registry-storage
      - masters
      - router
      terraform_dir: "{{ playbook_dir }}/terraform/{{ openshift_provision_cluster_name }}"

  - name: Wait for all instances to be running
    command: ../hosts.py --wait 300
    changed_when: false

  - name: Refresh inventory
    meta: refresh_inventory

- name: Wait for instances
  hosts: OSEv3
  gather_facts: false
  tasks:
  - name: Wait for connection to instances
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
